steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]

  # Deploy
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "deploy:PR", "${_SAFE_BRANCH_NAME}"]
substitutions:
  _SAFE_BRANCH_NAME: ${BRANCH_NAME//\//-}
