# This is a basic workflow to help you get started with Actions

name: CI Lint and test Check 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:

    runs-on: ubuntu-latest

    # Node versions can be added for this action pls note that version 8 causes problems
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Installing dependencies
    - run: npm ci
    # Running and checking build script
    - run: npm run build --if-present
    # Run ESLint
    - uses: eslint/github-action@v0
    # Env with CI true needs to be added or else this action will break
    - run: npm run test
      env:
        CI: true   
  


