# This is a basic workflow to help you get started with Actions

name: CI PR on MasterBranch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm run test
    #   env:
    #     CI: true   

    # Check out the repository
    - uses: actions/checkout@v1

    # Install Node.js
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    # Install your dependencies
    - run: npm ci

    # Run ESLint
    - uses: eslint/github-action@v0
  


